# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

workspace:
  clean: all
  
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: CmdLine@2
  displayName: "Clone static website git"
  inputs:
    script: 'git clone https://github.com/praveenjindal62/static-website-template.git'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)\azure-static-website-storage-explorer'
    backendServiceArm: 'Visual Studio Professional Subscription(1)(a5917f77-047e-4ec0-bbf9-49b052c5ee62)'
    backendAzureRmResourceGroupName: 'terraform-global'
    backendAzureRmStorageAccountName: 'terraformstatepjepam'
    backendAzureRmContainerName: 'terraformstate'
    backendAzureRmKey: 'terraform.tfstate'

